#include<iostream.h>
#include<conio.h>
void main()
{
int a[100],b,c,i,f=0,d,e,x,y,z;
clrscr();
cout<<"the prime numbers within 35 are...\n" ;
for(b=1;b<35;b++)
{
for(i=1;i<=e;i++)
{
f++;
}
for(int j=0;f==2;j++)
{
a[j]=i;
cout<<a[j]<<"\n";
}
}
for(c=0;;)
{
for(d=c;;d++)
{
x=a[d];y=a[d+1];z=a[d+2];
if((x+y+z)=83)
break;
}
break;
}
cout<<"the first value is "<<x;
cout<<"the second value is "<<y;
cout<<"the third value is "<<z;
getch();
}